project:
  type: website
  output-dir: docs

website:
  title: "Instituto contra la Leucemia Josep Carreras"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Publicaciones.qmd
        text: Publicaciones
    right:
      - icon: twitter
        text: Twitter
        href: https://x.com/CarrerasIJC?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
      - icon: github
        text: GitHub
        href: https://github.com/Kevin-Megias/primeraweb
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
